name: AlphaFold2-Multimer
description: "Predict multi-chain protein structures with AlphaFold2-Multimer"
engine: NEXTFLOW
main: main.nf
parameterTemplate:
  fasta_path: 
    description: "Input file in multi-FASTA format."
    optional: true
storageType: "DYNAMIC"
tags:
  Name: "AlphaFold2Multimer"